### ISSUE TITLE
Problem with paper-input inside paper-item

### ISSUE THREAD

**Issue by beppino** [PolymerElements/paper-item#28]
Hello,
I'm not sure if the problem is about paper-item or paper-input, but if I use a paper-input inside a paper-icon-item the input doesn't accept space character.
It's a new problem, from the last few days... Can please help me? I've an application in beta testing and my client ask me for a solution.
Thanks!
-g

**Comment by beppino** [comment]
I think that the problem it's inserted by the last commit on the element by @cdata  (https://github.com/PolymerElements/paper-item/commit/eb3b45d106c1f4e1f898e3741d3d7e29daced193). The insertion of the Polymer.IronButtonState behavior block the space and enter keyboard input and the paper-input, inside the paper-item, doesn't accept these characters.
Please, if this is the problem, let me know.
-g

**Comment by notwaldorf** [comment]
Yup, you're correct. The problem is that `paper-item` has become a button, and is handling the `space` key as a button activation, so it doesn't get to the `paper-input`. I'm working on a fix -- it's a bit slower because I tried to figure out what the platform does in this case re: button activation (http://jsbin.com/tilogitavu/1/edit?html,output) and there's no good answer (it depends on the browser)

I'll hopefully have something ready by tomorrow. Sorry about this, in the meantime.

**Comment by Sinjins** [comment]
@notwaldorf ...in addition to the space issue, now that paper-item has become a button it seems that tab indexing has also become an issue, as paper-item (or paper-icon-item in my case) now receives focus on tabbing, rather than a paper-input inside of paper-icon-item.

**Comment by beckula** [comment]
I also see it happening with arrow left/right key events as well.

**Comment by notwaldorf** [comment]
@Sinjins for that, you could make the parent `paper-item` have a tabindex of -1:
```html
<paper-item tabindex="-1"><input></paper-item>
```

**Comment by michael-lumley** [comment]
Where do we stand on this currently? Is there a temporary work around?

**Comment by beppino** [comment]
I've simply commented the use of the IronButtonState behavior in both paper-item and paper-icon-item.
I don't know if this can create some other problem, but after some weeks of development, nothing appear to me.
<pre>
behaviors: [
  Polymer.IronControlState/*,
  Polymer.IronButtonState*/
]
</pre>

**Comment by michael-lumley** [comment]
That seems to have worked as a temporary patch. Thanks! I opened a [stack overflow question](http://stackoverflow.com/questions/33258752/polymer-nesting-paper-input-under-paper-item-disables-spacebar/33278528#33278528) on this topic - happy to give you credit there, if you'd like.

**Comment by LoveAndHappiness** [comment]
Am using ´Polymer 1.2.2´ and the problem still exists.

**Comment by beppino** [comment]
I've to confirm, the problem still exists also for me.

**Comment by Sinjins** [comment]
I concur.  I've been using @beppino 's tactic until it is resolved.

**Comment by notwaldorf** [comment]
Yup, you're right, re-opening.

**Comment by notwaldorf** [comment]
Ok. It should REALLY be fixed now. I have tests that say so :)

Pull all your dependencies, etc... (the fix is in 'iron-behaviors`)

**Comment by mrtedgeesq** [comment]
I still seem to be getting this problem at:
Polymer 1.6.1
paper-item 1.2.1
iron-behaviors 1.0.17

**Comment by hyyan** [comment]
Any news about this issue ?

**Comment by SPessall** [comment]
We also still have this problem, but I just realized that it only occurs when the paper-input is injected via the content-tag inside the paper-item.

If the paper-item directly contains the paper-input the space is correctly added to the input field.

**Comment by schlm3** [comment]
I still have this kind of problem with iron-behaviours 1.0.18, used by paper-item 1.2.2.
It might also be related with the <content>.
